### ISSUE TITLE
Correct the url of the enhydris-openhigis module

### ISSUE THREAD

**Issue by dkalog** [openmeteo/openhi-docker-dev#3]
[submodule "enhydris"]
        path = enhydris
        url = https://github.com/openmeteo/enhydris.git
[submodule "enhydris-openhigis"]
        path = enhydris-openhigis
        url = ./enhydris-openhigis/
[submodule "enhydris-synoptic"]
        path = enhydris-synoptic
        url = git@github.com:openmeteo/enhydris-synoptic
[submodule "enhydris-autoprocess"]
        path = enhydris-autoprocess
        url = git@github.com:openmeteo/enhydris-autoprocess

I used this : 
[submodule "enhydris"]
        path = enhydris
        url = git@github.com:openmeteo/enhydris
[submodule "enhydris-openhigis"]
        path = enhydris-openhigis
        url = git@github.com:openmeteo/enhydris-openhigis
[submodule "enhydris-synoptic"]
        path = enhydris-synoptic
        url = git@github.com:openmeteo/enhydris-synoptic
[submodule "enhydris-autoprocess"]
        path = enhydris-autoprocess
        url = git@github.com:openmeteo/enhydris-autoprocess

**Comment by aptiko** [comment]
This was fixed ages ago (actually on the same day as this issue was filed) in 38dca968179d7913241283bf6cbca4832e353c48, and it doesn't matter anyway because soon after we stopped working with submodules in 06e5604c717a0de46aa5885627a2c131e280714f.
