### ISSUE TITLE
Make docker run Selenium tests on a visible browser

### ISSUE THREAD

**Issue by aptiko** [openmeteo/openhi-docker-dev#7]
Go figure how this is done. I asked a [question on StackOverflow](https://stackoverflow.com/questions/62011537/how-can-i-run-selenium-tests-in-a-docker-container-with-a-visible-browser) but I'm not satisfied with the results.

On GNU/Linux/etc., maybe somehow setting the `DISPLAY` environment variable could make it work. On Windows, I can't think of a way to do it without connecting to the container with VNC or a similar technology.

The StackOverflow answers may have more ideas.

**Comment by dkalog** [comment]
I have created a branch with a VNC aware docker. You can connect via vnc with _password_ password

**Comment by aptiko** [comment]
File `xstartup` seems to be missing.

    COPY xstartup /root/.vnc/
    COPY failed: stat /var/lib/docker/tmp/docker-builder934133230/xstartup: no such file or directory
